### ISSUE TITLE
Private data length on a DGX-2 exceeds sockcm's maximum

### ISSUE THREAD

**Issue by pentschev** [openucx/ucx#4842]
### Describe the bug
Private data length on a DGX-2 exceeds maximum `sockcm`'s maximum of 1024.

### Steps to Reproduce
- I'm currently only able to reproduce this with UCX-Py, but can try to work on an example that depends only on UCX core;
- UCX versions: `v1.7.0`, `master`:
- UCX environment variables: `UCX_MEMTYPE_CACHE=n UCX_TLS=rc,sockcm,tcp,cuda_copy UCX_SOCKADDR_TLS_PRIORITY=sockcm`.

### Setup and versions
- DGX-2 systems only;
- Does not happen unless `rc` is enabled in `UCX_TLS`;
- `libibverbs` version `41mlnx1-OFED.4.4.2.0.1.44207`;
- CUDA 10.1, driver version `418.87.00`.

### Additional information (depending on the issue)
- Specifying `UCX_TLS` is required on DGX-2, otherwise we get an error `exceeded transports/devices limit (70 requested, up to 64 are supported)`;
- Error report:
```
[1583334371.228270] [dgx202:13546:0]      wireup_ep.c:486  UCX  ERROR no supported sockaddr auxiliary transports found for enp134s0f1
[1583334371.228287] [dgx202:13546:0]      sockcm_ep.c:76   UCX  ERROR sockcm client (iface=0x7fb234590f60, ep = 0x7fb2342e7fc0) failed to fill private data. status: Destination is unreachable
[1583334371.228292] [dgx202:13546:0]      sockcm_ep.c:155  UCX  ERROR failed to send client info: Input/output error
```

### Failing codepath
- The check in https://github.com/openucx/ucx/blob/master/src/ucp/wireup/wireup_ep.c#L535 currently evaluates to true and attempts to pack sockaddr auxiliary TLS, which also fails.

### Proposed Solution
- Increase the value of [`UCT_SOCKCM_PRIV_DATA_LEN`](https://github.com/openucx/ucx/blob/master/src/uct/tcp/sockcm/sockcm_def.h#L22). The size I've seen is around 1500 bytes, so a safer size would be `4096`, but `2048` should suffice as well.
- In my tests, the solution above worked as expected and I didn't experience any issues due to that change.

**Comment by pentschev** [comment]
cc @quasiben @Akshay-Venkatesh

**Comment by pentschev** [comment]
This would address #4557 .

**Comment by yosefe** [comment]
@pentschev can you try adding `UCX_SOCKADDR_AUX_TLS=ud_verbs`?

**Comment by pentschev** [comment]
@yosefe I don't know if you still wanted me to test `UCX_SOCKADDR_AUX_TLS=ud_verbs`, but just for future reference, that didn't solve the issue.

As per our conversation during the UCX call earlier today, I filed #4905 increasing `UCT_SOCKCM_PRIV_DATA_LEN` to `2048`, and a backport of that to v1.8 in #4906.

**Comment by evgeny-leksikov** [comment]
@pentschev is there any practical reason to listen and connect with sockcm but communicate with IB/RC? why not rdmacm?
UCX_TLS=**rc**,sockcm,tcp,cuda_copy
UCX_SOCKADDR_TLS_PRIORITY=**sockcm**

**Comment by pentschev** [comment]
To be honest, I'm not quite sure why we can't do that. What I know is that using `rdmacm` won't open TCP ports we need to establish connections with Dask/UCX-Py. @Akshay-Venkatesh I think you know more details, could you briefly explain why that's not possible today?

**Comment by evgeny-leksikov** [comment]
@Akshay-Venkatesh could you please describe a use case why does Dask/UCX-Py establish connection to TCP port and not using rdmacm when IB fabric is available?

**Comment by pentschev** [comment]
Just to be more specific, if I specify `rdmacm` in replacement of `sockcm`, the error I get is:

```
[1585658991.029584] [dgx12:54012:0]   ucp_listener.c:431  UCX  ERROR none of the available transports can listen for connections on 0.0.0.0:8786
```

**Comment by evgeny-leksikov** [comment]
@pentschev seems like there is no either IPoIB or RoCE configured iface... can you share `ifconfig` output or check it by yourself?

**Comment by pentschev** [comment]
We do have 4 IPoIB interfaces, this is a a DGX-1, they're all configured the same way, as below:

```
ib0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 2044
        inet 10.33.225.162  netmask 255.255.254.0  broadcast 10.33.225.255
        inet6 fe80::526b:4b03:28:d0f2  prefixlen 64  scopeid 0x20<link>
        unspec 20-00-10-95-FE-80-00-00-00-00-00-00-00-00-00-00  txqueuelen 256  (UNSPEC)
        RX packets 77395  bytes 7739500 (7.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1116  bytes 67056 (67.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by evgeny-leksikov** [comment]
@pentschev thanks! could you also share logs with `UCX_LOG_LEVEL=trace` ? thanks in advance!

**Comment by pentschev** [comment]
After a bit more testing, it seems that this was my mistake since in UCX-Py we currently preset `UCX_SOCKADDR_TLS_PRIORITY=sockcm` and I didn't realize my configurations weren't overriding that before. Now after switching to `UCX_TLS=rc,rdmacm,tcp,cuda_copy UCX_SOCKADDR_TLS_PRIORITY=rdmacm` things seem to work, I can have dask workers connect to dask scheduler that way. However, this only works within the same node, so if I have a scheduler on node A and workers on node B, the workers can't seem to reach node A, is that expected?

**Comment by evgeny-leksikov** [comment]
nice progress :) pls check that workers connect to IP address associated with IB iface on node A

**Comment by pentschev** [comment]
I double checked it, but the IP and port are correct. In the same node, connection is successful:

```
[1585669824.481946] [dgx12:71119:0]         select.c:200  UCX  TRACE cuda_copy/cuda : not suitable for high-bw remote memory access, no send completion event
[1585669824.481949] [dgx12:71119:0]         select.c:365  UCX  TRACE rc/mlx5_0:1 : disabled by tl_bitmap
[1585669824.481950] [dgx12:71119:0]         select.c:200  UCX  TRACE rdmacm/sockaddr : not suitable for high-bw remote memory access, no pending
[1585669824.481952] [dgx12:71119:0]         select.c:304  UCX  TRACE addr[0] cuda_copy: no tag eager bcopy
[1585669824.481953] [dgx12:71119:0]         select.c:304  UCX  TRACE addr[1] cuda_ipc: no tag eager bcopy
[1585669824.481956] [dgx12:71119:0]         select.c:200  UCX  TRACE cuda_copy/cuda : not suitable for auxiliary, no am bcopy
[1585669824.481961] [dgx12:71119:0]     ucp_worker.c:1491 UCX  INFO  ep_cfg[1]: rma(cuda_copy/cuda);
[1585669824.481963] [dgx12:71119:0]         wireup.c:796  UCX  DEBUG ep 0x7ff17e3de000: am_lane 255 wireup_lane 255 reachable_mds 0x1
[1585669824.481985] [dgx12:71119:0]         wireup.c:802  UCX  DEBUG ep 0x7ff17e3de000: lane[0]:  0:cuda_copy/cuda md[0]        -> addr[0].md[0]/cuda_cpy rma#0
[1585669824.481986] [dgx12:71119:0]         wireup.c:652  UCX  TRACE ep 0x7ff17e3de000: connect lane[0]
[1585669824.481988] [dgx12:71119:0]         wireup.c:664  UCX  TRACE ep 0x7ff17e3de000: connect uct_ep[0] to addr[0]
[1585669824.481991] [dgx12:71119:0]         wireup.c:614  UCX  TRACE ep 0x7ff17e3de000: assign uct_ep[0]=0x5615c2ab2620
[1585669824.481993] [dgx12:71119:0]     ucp_worker.c:598  UCX  TRACE activate iface 0x5615c29f5180 acount=0 aifaces=0
[1585669824.482024] [dgx12:71119:0]          mpool.c:88   UCX  DEBUG mpool ucp_am_bufs: align 64, maxelems 4294967295, elemsize 8271
[1585669824.482026] [dgx12:71119:0]          mpool.c:88   UCX  DEBUG mpool ucp_reg_bufs: align 64, maxelems 4294967295, elemsize 8208
[1585669824.482028] [dgx12:71119:0]          mpool.c:88   UCX  DEBUG mpool ucp_rndv_frags: align 64, maxelems 4294967295, elemsize 262160
[1585669824.482166] [dgx12:71119:0]         parser.c:1578 UCX  WARN  unused env variable: UCX_TCP_TX_SEG_SIZE,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
[1585669824.482177] [dgx12:71119:0]     ucp_worker.c:2003 UCX  TRACE ucp_worker_arm returning Success
[1585669824.791892] [dgx12:71119:0]      rdmacm_md.c:170  UCX  DEBUG address 0.0.0.0:50719 (port 50719) is accessible from rdmacm_md 0x5615c2542ca0 with mode: 0
[1585669824.792021] [dgx12:71119:0]   rdmacm_iface.c:552  UCX  DEBUG rdma_cm id 0x5615c2190db0 listening on 0.0.0.0:50719:50719
[1585669824.792028] [dgx12:71119:0]          async.c:205  UCX  DEBUG added async handler 0x5615c301bcc0 [id=41 ref 1] ???() to hash
[1585669824.792039] [dgx12:71119:0]          async.c:469  UCX  DEBUG listening to async event fd 41 events 0x1 mode thread_spinlock
[1585669824.792041] [dgx12:71119:0]   rdmacm_iface.c:583  UCX  DEBUG created an RDMACM iface 0x5615c2ad8190. event_channel: 0x5615c17e7ed0, fd: 41, cm_id: 0x5615c2190db0
[1585669824.792045] [dgx12:71119:0]     ucp_worker.c:1108 UCX  DEBUG created interface[4]=0x5615c2ad8190 using rdmacm/sockaddr on worker 0x5615c2a27b00
[1585669824.792048] [dgx12:71119:0]   ucp_listener.c:425  UCX  TRACE listener 0x5615c30844d0: accepting connections on rdmacm on 0.0.0.0:50719
[1585669825.135783] [dgx12:71119:0]         ucp_ep.c:131  UCX  DEBUG created ep 0x7ff17e3de048 to <no debug data> from api call
[1585669825.135792] [dgx12:71119:0]      wireup_ep.c:364  UCX  TRACE ep 0x7ff17e3de048: created wireup ep 0x5615c30d0900 to <no debug data>
[1585669825.142881] [dgx12:71119:0]      rdmacm_md.c:170  UCX  DEBUG address 10.33.225.162:8786 (port 33479) is accessible from rdmacm_md 0x5615c2542ca0 with mode: 1
[1585669825.143024] [dgx12:71119:0]         select.c:1474 UCX  DEBUG sockaddr transport selected: rdmacm
[1585669825.143034] [dgx12:71119:0]      rdmacm_ep.c:61   UCX  DEBUG ep 0x5615c6ae9f30, new cm_id 0x5615c6a91f10. cm_id_in_quota 63
[1585669825.143045] [dgx12:71119:0]      rdmacm_ep.c:166  UCX  DEBUG create[1585669825.143107] [dgx12:71119]          replace.c:31   UCX  TRACE ucm_override_mmap()
[1585669825.143116] [dgx12:71119]            event.c:173  UCX  TRACE ucm_mmap(addr=0x0 length=134217728 prot=0x0 flags=0x4022 fd=-1 offset=0)
[1585669825.143141] [dgx12:71119]            event.h:60   UCX  TRACE vm_map addr=0x7feaf0000000 length=134217728
[1585669825.143145] [dgx12:71119]          replace.c:32   UCX  TRACE ucm_override_munmap()
[1585669825.143147] [dgx12:71119]            event.c:206  UCX  TRACE ucm_munmap(addr=0x7feaf4000000 length=67108864)
[1585669825.143149] [dgx12:71119]            event.h:72   UCX  TRACE vm_unmap addr=0x7feaf4000000 length=67108864
[1585669825.155892] [dgx12:71119]          replace.c:31   UCX  TRACE ucm_override_mmap()
[1585669825.155898] [dgx12:71119]            event.c:173  UCX  TRACE ucm_mmap(addr=0x0 length=4329472 prot=0x3 flags=0x22 fd=-1 offset=0)
[1585669825.155906] [dgx12:71119]            event.h:60   UCX  TRACE vm_map addr=0x7ff170513000 length=4329472
[1585669825.155965] [dgx12:71119]          replace.c:40   UCX  TRACE ucm_override_madvise()
[1585669825.155967] [dgx12:71119]            event.c:414  UCX  TRACE ucm_madvise(addr=0x7ff170513000 length=4329472 advice=10)
d an RDMACM endpoint on iface 0x5615c2acdcb0. event_channel: 0x5615c28e45b0, iface cm_id: (nil) remote addr: 10.33.225.162:8786
[1585669825.143052] [dgx12:71119:0]      wireup_ep.c:621  UCX  DEBUG ep 0x7ff17e3de048 connecting to 10.33.225.162:8786
[1585669825.143318] [dgx12:71119:1]   rdmacm_iface.c:293  UCX  TRACE rdmacm event (fd=37 cm_id 0x5615c6a91f10) on client (ep=0x5615c6ae9f30): RDMA_CM_EVENT_ADDR_RESOLVED. Peer: 10.33.225.162:8786.
[1585669825.143361] [dgx12:71119:0]          mpool.c:205  UCX  DEBUG mpool ucp_requests: allocated chunk 0x5615c6a92164 of 41044 bytes with 128 elements
[1585669825.143392] [dgx12:71119:0]         wireup.c:1024 UCX  TRACE ep 0x7ff17e3de048: connect lane 0 to remote peer
[1585669825.143715] [dgx12:71119:1]   rdmacm_iface.c:293  UCX  TRACE rdmacm event (fd=37 cm_id 0x5615c6a91f10) on client (ep=0x5615c6ae9f30): RDMA_CM_EVENT_ROUTE_RESOLVED. Peer: 10.33.225.162:8786.
[1585669825.143732] [dgx12:71119:1]        address.c:685  UCX  TRACE pack addr[0] : cuda_copy/cuda md_flags 0x2 tl_flags 0x10000000558 bw 0.000000e+00 + 7.246709e+09/n ovh 0.000000e+00 lat_ovh 1.000000e-05 dev_priority 0 a32 0x0/0x0 a64 0x0/0x0
[1585669825.143739] [dgx12:71119:1]        address.c:685  UCX  TRACE pack addr[1] : cuda_ipc/cuda md_flags 0x2 tl_flags 0xc14000000448 bw 0.000000e+00 + 2.516582e+10/n ovh 0.000000e+00 lat_ovh 1.000000e-09 dev_priority 0 a32 0x0/0x0 a64 0x0/0x0
[1585669825.143744] [dgx12:71119:1]        address.c:685  UCX  TRACE pack addr[2] : rc/mlx5_0:1 md_flags 0x2 tl_flags 0xd2408000067f bw 0.000000e+00 + 1.236715e+10/n ovh 7.500000e-08 lat_ovh 8.000000e-07 dev_priority 30 a32 0x0/0x0 a64 0x1/0x21
[1585669825.143748] [dgx12:71119:1]        address.c:685  UCX  TRACE pack addr[3] : ud/mlx5_0:1 md_flags 0x2 tl_flags 0xf3400000000f bw 0.000000e+00 + 1.236715e+10/n ovh 1.050000e-07 lat_ovh 8.100000e-07 dev_priority 30 a32 0x0/0x0 a64 0x0/0x0
[1585669825.155851] [dgx12:71119:0]          ud_ep.c:208  UCX  DEBUG created ep ep=0x5615c6a9c1c0 iface=0x5615c2ab2a60 id=0
```

If I try to connect to the same dask scheduler but from a different node it fails:

```
[1585669832.578348] [dgx13:81379:1]      uct_iface.c:326  UCX  DEBUG set ep 0x56085bc8b110 to failed state
[1585669832.578350] [dgx13:81379:1]      rdmacm_ep.c:181  UCX  DEBUG rdmacm_ep 0x56085bc8b110: destroying
[1585669832.578352] [dgx13:81379:1]      rdmacm_ep.c:204  UCX  DEBUG ep destroy: cm_id 0x56085bc8b220
[1585669832.578353] [dgx13:81379:1]     ucp_worker.c:569  UCX  DEBUG worker 0x560857c37630: error handler called for uct_ep 0x56085bc8b110: Destination is unreachable
[1585669832.578379] [dgx13:81379:1]   rdmacm_iface.c:252  UCX  TRACE destroying cm_id 0x56085bc8b220
[1585669832.578622] [dgx13:81379:0]     ucp_worker.c:2003 UCX  TRACE ucp_worker_arm returning Device is busy
[1585669832.578645] [dgx13:81379:0]     ucp_worker.c:2003 UCX  TRACE ucp_worker_arm returning Success
[1585669832.578716] [dgx13:81379:0]     ucp_worker.c:2003 UCX  TRACE ucp_worker_arm returning Success
[1585669833.577601] [dgx13:81379:0]         ucp_ep.c:131  UCX  DEBUG created ep 0x7f34ad59a0d8 to <no debug data> from api call
[1585669833.577607] [dgx13:81379:0]      wireup_ep.c:364  UCX  TRACE ep 0x7f34ad59a0d8: created wireup ep 0x560857b07890 to <no debug data>
[1585669833.578346] [dgx13:81379:0]      rdmacm_md.c:170  UCX  DEBUG address 10.33.225.162:8786 (port 54079) is accessible from rdmacm_md 0x5608575a7c80 with mode: 1
[1585669833.578584] [dgx13:81379:0]         select.c:1474 UCX  DEBUG sockaddr transport selected: rdmacm
[1585669833.578592] [dgx13:81379:0]      rdmacm_ep.c:61   UCX  DEBUG ep 0x56085bc8b760, new cm_id 0x56085bc8b8a0. cm_id_in_quota 63
[1585669833.578613] [dgx13:81379:0]      rdmacm_ep.c:166  UCX  DEBUG created an RDMACM endpoint on iface 0x560857cdd1f0. event_channel: 0x560857aa3d40, iface cm_id: (nil) remote addr: 10.33.225.162:8786
[1585669833.578616] [dgx13:81379:0]      wireup_ep.c:621  UCX  DEBUG ep 0x7f34ad59a0d8 connecting to 10.33.225.162:8786
[1585669833.578733] [dgx13:81379:1]   rdmacm_iface.c:293  UCX  TRACE rdmacm event (fd=37 cm_id 0x56085bc8b8a0) on client (ep=0x56085bc8b760): RDMA_CM_EVENT_ADDR_RESOLVED. Peer: 10.33.225.162:8786.
[1585669833.578769] [dgx13:81379:0]         wireup.c:1024 UCX  TRACE ep 0x7f34ad59a0d8: connect lane 0 to remote peer
[1585669833.579001] [dgx13:81379:1]   rdmacm_iface.c:293  UCX  TRACE rdmacm event (fd=37 cm_id 0x56085bc8b8a0) on client (ep=0x56085bc8b760): RDMA_CM_EVENT_ROUTE_RESOLVED. Peer: 10.33.225.162:8786.
[1585669833.579013] [dgx13:81379:1]        address.c:685  UCX  TRACE pack addr[0] : cuda_copy/cuda md_flags 0x2 tl_flags 0x10000000558 bw 0.000000e+00 + 7.246709e+09/n ovh 0.000000e+00 lat_ovh 1.000000e-05 dev_priority 0 a32 0x0/0x0 a64 0x0/0x0
[1585669833.579019] [dgx13:81379:1]        address.c:685  UCX  TRACE pack addr[1] : cuda_ipc/cuda md_flags 0x2 tl_flags 0xc14000000448 bw 0.000000e+00 + 2.516582e+10/n ovh 0.000000e+00 lat_ovh 1.000000e-09 dev_priority 0 a32 0x0/0x0 a64 0x0/0x0
[1585669833.579023] [dgx13:81379:1]        address.c:685  UCX  TRACE pack addr[2] : rc/mlx5_0:1 md_flags 0x2 tl_flags 0xd2408000067f bw 0.000000e+00 + 1.236715e+10/n ovh 7.500000e-08 lat_ovh 8.000000e-07 dev_priority 30 a32 0x0/0x0 a64 0x1/0x21
[1585669833.579027] [dgx13:81379:1]        address.c:685  UCX  TRACE pack addr[3] : ud/mlx5_0:1 md_flags 0x2 tl_flags 0xf3400000000f bw 0.000000e+00 + 1.236715e+10/n ovh 1.050000e-07 lat_ovh 8.100000e-07 dev_priority 30 a32 0x0/0x0 a64 0x0/0x0
[1585669833.579152] [dgx13:81379:1]   rdmacm_iface.c:293  UCX  TRACE rdmacm event (fd=37 cm_id 0x56085bc8b8a0) on client (ep=0x56085bc8b760): RDMA_CM_EVENT_UNREACHABLE. Peer: 10.33.225.162:8786.
[1585669833.579154] [dgx13:81379:1]   rdmacm_iface.c:409  UCX  ERROR received event RDMA_CM_EVENT_UNREACHABLE. status = 2. Peer: 10.33.225.162:8786.
```

What's interesting is that I can confirm transfer between these two nodes with `ucx_perftest`.

**Comment by pentschev** [comment]
I'm trying to compare the trace logs now to establish where the issue seems to be coming from, and everything seems to happen the exact same way in both local and remote until `RDMA_CM_EVENT_UNREACHABLE`. I also looked at the `ucx_perftest` logs to compare, but connection seems to be happening in a different way as I don't see any mentions of the processes' IP addresses in that log, even when running server/client on different nodes.

I'm not sure whether we're trying to establish the connection in a way that's not expected by rdmacm, any ideas are much appreciated @evgeny-leksikov !

**Comment by evgeny-leksikov** [comment]
@pentschev thanks for investigation!
 - you can try to run `ib_send_lat` test (https://github.com/linux-rdma/perftest/blob/master/src/send_lat.c, most likely it's already installed on your system) to check rdmacm setup correctness on the same devices and hosts with ` --rdma_cm` parameter
 - could you please share full UCX logs from both server and client? `test/examples/ucp_client_server.c` may be simpler for debugging.

**Comment by pentschev** [comment]
Thanks @evgeny-leksikov , I can reproduce the same issue with `test/examples/ucp_client_server.c`. I've uploaded logs for client and server in both single node and multinode configurations in https://gist.github.com/pentschev/a64d669760192ac94ef874aba127d2ba.

With `ib_send_lat` I am able to run it without any options:

```
$ ib_send_lat

************************************
* Waiting for client to connect... *
************************************
---------------------------------------------------------------------------------------
                    Send Latency Test
 Dual-port       : OFF          Device         : mlx5_1
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 RX depth        : 512
 Mtu             : 4096[B]
 Link type       : IB
 Max inline data : 236[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0x27 QPN 0x3d575 PSN 0xeb092a
 remote address: LID 0x2d QPN 0x271b1 PSN 0xe5f85c
---------------------------------------------------------------------------------------
 #bytes #iterations    t_min[usec]    t_max[usec]  t_typical[usec]    t_avg[usec]    t_stdev[usec]   99% percentile[usec]   99.9% percentile[usec]
Conflicting CPU frequency values detected: 3307.144000 != 3191.519000. CPU Frequency is not max.
Conflicting CPU frequency values detected: 3534.190000 != 3325.551000. CPU Frequency is not max.
 2       1000          1.15           2.74         1.18                1.18             0.02            1.23            2.74
---------------------------------------------------------------------------------------
```

```
$ ib_send_lat 10.33.225.162
---------------------------------------------------------------------------------------
                    Send Latency Test
 Dual-port       : OFF          Device         : mlx5_1
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 TX depth        : 1
 Mtu             : 4096[B]
 Link type       : IB
 Max inline data : 236[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0x2d QPN 0x271b1 PSN 0xe5f85c
 remote address: LID 0x27 QPN 0x3d575 PSN 0xeb092a
---------------------------------------------------------------------------------------
 #bytes #iterations    t_min[usec]    t_max[usec]  t_typical[usec]    t_avg[usec]    t_stdev[usec]   99% percentile[usec]   99.9% percentile[usec]
Conflicting CPU frequency values detected: 3079.235000 != 2509.960000. CPU Frequency is not max.
Conflicting CPU frequency values detected: 2528.675000 != 2304.736000. CPU Frequency is not max.
 2       1000          1.14           5.53         1.18                1.18             0.02            1.22           5.53
---------------------------------------------------------------------------------------
```

If I try with `-R` it fails (see below), I'm not sure whether this is the option or if it's the only option I should be testing, but if you need me to do some more tests, please just let me know.

```
$ ib_send_lat -R

************************************
* Waiting for client to connect... *
************************************
```

```
$ ib_send_lat -R 10.33.225.162
Unexpected CM event bl blka 8
 Unable to perform rdma_client function
 Unable to init the socket connection
```

**Comment by alinask** [comment]
@pentschev Do you have rdmacm loaded on your hosts?
What is the output you get for:
`ls /dev/infiniband/rdma_cm`

**Comment by pentschev** [comment]
Yes, I checked each host and see the same for all:

```
$ ls -l /dev/infiniband/rdma_cm
crw-rw-rw- 1 root root 10, 54 Feb 14 08:41 /dev/infiniband/rdma_cm
```

**Comment by evgeny-leksikov** [comment]
@pentschev behaviour of `ib_send_lat -R` and UCX/rdmacm are the same - client can't reach server but according to UCX logs addr and route are resolved. looks like firewall...
can you `ping` server IP bound to IB device from client node?

**Comment by pentschev** [comment]
Yes, I can ping each other and I can run `ib_send_lat` as long as I don't include `-R`. I tested client/server in both ways on these two hosts and it seems to work without `-R`.

I'm sorry about my ignorance of rdmacm, I tested `ib_send_lat -R` in hosts of 3 different DGX-1 clusters we have, 2 of them fail and the third succeeds. It does sound like we have configuration issues in the two failing clusters. Would you be able to recommend a way I can troubleshoot these issues furthers and fix the clusters?

**Comment by evgeny-leksikov** [comment]
@pentschev thanks for update! i hope you can find something useful [here](https://community.mellanox.com/s/article/How-To-Enable-Verify-and-Troubleshoot-RDMA ) or [here](https://community.mellanox.com/s/question/0D51T00006RVtlUSAT/rdmacm-connection-setup-issues)

**Comment by pentschev** [comment]
Thanks @evgeny-leksikov and @alinask , I'll try to figure that out and report back as soon as I find something.

**Comment by pentschev** [comment]
Just a quick feedback about the previous discussion here @evgeny-leksikov , our devops team has still not been able to work on fixing the rdmacm issue on the cluster we normally use for UCX-Py development, but I was able to run UCX-Py with rdmacm enabled on a different cluster. In this other cluster my brief testing has shown no problems using rdmacm.

With the above said, I will add support for rdmacm in UCX-Py when IB is in use as well. It may take some weeks until that's done because we depend on our cluster to be fixed so we can do more testing.

Another question: sockcm will continue to be supported in UCX, right? We intend to keep that as not all systems that will run UCX-Py will have IB interfaces.

**Comment by evgeny-leksikov** [comment]
@pentschev thanks for update and especially for adding rdmacm support to UCX-Py!
I started this conversation to make sure we don't miss something critical in new client-server connections management engine. sockcm will continue to be supported until we can replace it with new sockcm_cm.
We expect that migration should be transparent for users since it's API/ABI backward compatible.
The only known limitation for now is CM and traffic will work via the same transport layer, i.e. connections established with sockcm_cm will send traffic by TCP transport, rdmacm_cm - IB/RoCE.

**Comment by pentschev** [comment]
Thanks @evgeny-leksikov for clarifications.

> The only known limitation for now is CM and traffic will work via the same transport layer, i.e. connections established with sockcm_cm will send traffic by TCP transport, rdmacm_cm - IB/RoCE.

Does that mean that to use IB we will absolutely need rdmacm_cm, meaning we won't be able to use sockcm_cm (as we do with sockcm today) for IB?

**Comment by evgeny-leksikov** [comment]
@pentschev Not sure if absolutely but rdmacm/IB will work definitely better vs sockcm/IB. Also need to clarify if we really need sockcm/IB. It would be extremely helpful if you can find and share why rdmacm is not working on some DGX systems.

**Comment by pentschev** [comment]
> Not sure if absolutely but rdmacm/IB will work definitely better vs sockcm/IB. Also need to clarify if we really need sockcm/IB.

Thanks for clarifying.

> It would be extremely helpful if you can find and share why rdmacm is not working on some DGX systems.

Will do once our devops team has the chance to work on that, I can't promise it will be very soon though, perhaps that won't happen until May.
