### ISSUE TITLE
UCX 1.9.0: configure script insists on cray-ugni support

### ISSUE THREAD

**Issue by ca-taylor** [openucx/ucx#5731]
### Describe the bug
configure script insists on cray-ugni support even when --without-ugni is given on the configure command line.

### Steps to Reproduce
- ./configure --without-ugni
- UCX 1.9.0

### Setup and versions
Red Hat Enterprise Linux Server release 7.7 (Maipo)
Linux login4.ufhpc 3.10.0-1062.18.1.el7.x86_64 #1 SMP Wed Feb 12 14:08:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --with-ugni=no --enable-cma --without-cuda --without-gdrcopy --with-verbs --without-cm --without-knem --with-rdmacm --without-rocm --without-xpmem --enable-stats --enable-mt --with-avx --with-verbs --with-rc --with-ud --with-dc --with-rdmacm --with-mlx5-dv --with-ib-hw-tm --with-dm --without-cm --without-ugni
....
checking for CRAY_UGNI... no
configure: WARNING: UGNI support was requested but cray-ugni and cray-pmi packages can't be found
configure: error: Cannot continue

**Comment by ca-taylor** [comment]
The patch does not resolve the issue.

commit b8b3caf11c9229f5ece82a8ba384a5f2e859a310
Author: Pavel Shamis (Pasha) <pasharesearch@gmail.com>
Date:   Sun Sep 27 12:16:45 2020 -0500

    Fix for https://github.com/openucx/ucx/issues/5731

-----------------------------------------------------------

+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --with-ugni=no --enable-cma --without-cuda --without-gdrcopy --with-verbs --without-cm --without-knem --with-rdmacm --without-rocm --without-xpmem --enable-stats --enable-mt --with-avx --with-verbs --with-rc --with-ud --with-dc --with-rdmacm --with-mlx5-dv --with-ib-hw-tm --with-dm --without-cm
checking for x86_64-redhat-linux-gnu-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
...
checking for CRAY_UGNI... no
configure: WARNING: UGNI support was requested but cray-ugni and cray-pmi packages can't be found
configure: error: Cannot continue
error: Bad exit status from /var/tmp/rpm-tmp.IrSzsk (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.IrSzsk (%build)

**Comment by hiroyuki-sato** [comment]
Hello, @ca-taylor 

I'm not familiar cray-ugni. But

It seems that the latest commit No in [#5745](https://github.com/openucx/ucx/pull/5745) is ebae13e1bff6889818c1e59785ddeee34e84fb75
It's not b8b3caf11c9229f5ece82a8ba384a5f2e859a310 (from your comment)

The following command show c82bdaf3415496c7696c47d2feef953175b5485d in my environment.

```
git remote add shamisp https://github.com/shamisp/ucx/
git fetch shamisp
git checkout -b shamisp/topic/ugni/config  shamisp/topic/ugni/config
git log
```

**Comment by shamisp** [comment]
@ca-taylor my patch was buggy. Should be fixed now.

**Comment by ca-taylor** [comment]
Can you point me to the commit?

**Comment by shamisp** [comment]
This is the PR: https://github.com/openucx/ucx/pull/5745
Full patch https://patch-diff.githubusercontent.com/raw/openucx/ucx/pull/5745.patch

**Comment by ca-taylor** [comment]
AFAICT, the patch does NOT fix the problem...

+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --with-ugni=no --enable-cma --without-cuda --without-gdrcopy --with-verbs --without-cm --without-knem --with-rdmacm --without-rocm --without-xpmem --enable-stats --enable-mt --with-avx --with-verbs --with-rc --with-ud --with-dc --with-rdmacm --with-mlx5-dv --with-ib-hw-tm --with-dm --without-cm
checking for x86_64-redhat-linux-gnu-gcc... no
checking for gcc... gcc
....
checking for rdma_create_id in -lrdmacm... yes
checking for CRAY_UGNI... no
configure: WARNING: UGNI support was requested but cray-ugni and cray-pmi packages can't be found
configure: error: Cannot continue

**Comment by shamisp** [comment]
Did you re-run autogen.sh after applying the patch ?

**Comment by hiroyuki-sato** [comment]
> configure: WARNING: UGNI support was requested but cray-ugni and cray-pmi packages can't be found

This message doesn't contains the latest commit. The latest commit uses **cannot** instead of **can't**

```m4
              AS_IF([test "x$with_ugni" != "x"],
                    [AC_MSG_ERROR([UGNI support was requested but cray-ugni and cray-pmi packages cannot be found])])
             ])])
```

Could you try? before the `configure`

```
git remote add shamisp https://github.com/shamisp/ucx/
git fetch shamisp
git checkout -b shamisp/topic/ugni/config  shamisp/topic/ugni/config
./autogen.sh
```

**Comment by shamisp** [comment]
Ping @ca-taylor

**Comment by ca-taylor** [comment]
Running autogen.sh ahead of configure in my spec file seems to have resolved the issue.   My apologies for not doing that from the start.

**Comment by shamisp** [comment]
Thanks for checking !
